import platform

SYS_LIBS = []
DL_LIBS = ['dl']
CIGI_LIBS = []
BULLET_LIBS = []
SDL_LIBS = ['SDL']
SDL2_LIBS = ['SDL2']
PTHREAD_LIBS = []
DX_LIBS = []
DX11_LIBS = []
GL_LIBS = []
MAXSDK_LIBS = []
LUASTATIC_LIBS = []
TBB_LIBS_DEBUG = ['tbb_debug']
TBB_LIBS_RELEASE = ['tbb']
BOOST_LIBS = ['boost_date_time', 'boost_filesystem', 'boost_iostreams', 'boost_system', 'boost_thread', 'boost_wave']
NVTT_LIBS = ['nvtt']
PGF_LIBS = ['pgf']
LUA_LIBS = ['lua']
SPEEDTREE_LIBS = ['speedtree']
PHYSFS_LIBS = ['physfs']
GEOGRAPHICLIB_LIBS = ['geographiclib']
PREDICATES_LIBS = ['predicates']
NEDMALLOC_LIBS = ['nedmalloc']
FREETYPE_LIBS = ['freetype']
MD5_LIBS = ['md5']
OSGMATH_LIBS = ['OsgMath']
JPEG_LIBS = ['jpeg']
PNG_LIBS = ['png']
TIFF_LIBS = ['tiff']
ZLIB_LIBS = ['zlib']

if platform.system() == 'Linux':
    SYS_LIBS += ['rt'] # Only for Linux not for Mac
    GL_LIBS += ['GL']
