Import('env')

env.SConscript([
	'Core/SConscript.edge',
	'Server/Server.scons',
	'Client/Client.scons',
	'Proxy/Proxy.scons',
	'PoolSwitcher/PoolSwitcher.scons',
	'ServerTest/ServerTest.scons',
	'ClientTest/ClientTest.scons'
])
