Import('env')

env.SConscript([
	'Core/SConscript.edge',
	'QtHlp/SConscript.edge',
	'Server/Server.scons',
	'Client/Client.scons',
	'Proxy/Proxy.scons',
	'PoolSwitcher/PoolSwitcher.scons',
	'ServerTest/ServerTest.scons',
	'ClientTest/ClientTest.scons',
	'find/find.scons',
	'qt_server/qt_server.scons',
	'qt_client/qt_client.scons',
	'qt_server2/qt_server2.scons',
	'qt_client2/qt_client2.scons'
])
